enum ActionKind {
    Walking,
    Idle,
    Jumping
}
namespace SpriteKind {
    export const Gapkind = SpriteKind.create()
}
sprites.onOverlap(SpriteKind.Player, SpriteKind.Gapkind, function (sprite, otherSprite) {
    if (otherSprite.right - sprite.left < 2) {
        info.changeScoreBy(1)
    }
})
controller.anyButton.onEvent(ControllerButtonEvent.Pressed, function () {
    Mysprite.vy = -100
    animation.setAction(Mysprite, ActionKind.Jumping)
    Mysprite.startEffect(effects.rings, 300)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Projectile, function (sprite, otherSprite) {
    game.gameOver(false)
})
let projectile: Sprite = null
let gapSprite: Sprite = null
let gapimage: Image = null
let Bottom: Image = null
let Tops: Image = null
let gap = 0
let Mysprite: Sprite = null
scene.setBackgroundColor(9)
info.setScore(0)
effects.blizzard.startScreenEffect()
Mysprite = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . f f f f f f . . . . 
    . . . . f f 1 1 1 1 f 1 f . . . 
    . . . f 1 1 5 5 5 f 1 1 1 f . . 
    . f f f f 5 5 5 f 1 1 f 1 1 f . 
    f 1 1 1 1 f 5 5 f 1 1 f 1 1 f . 
    f 1 1 1 1 1 f 5 f 1 1 1 1 1 f . 
    f 5 1 1 1 5 f 5 5 f f f f f f f 
    . f 5 5 5 f 5 5 f 2 2 2 2 2 2 f 
    . . f f f 4 4 f 2 f f f f f f f 
    . . . f 4 4 4 4 f 2 2 2 2 2 2 f 
    . . . . f f 4 4 4 f f f f f f . 
    . . . . . . f f f . . . . . . . 
    . . . . . . . . . . . . . . . . 
    `, SpriteKind.Player)
Mysprite.ay = 300
let anim = animation.createAnimation(ActionKind.Jumping, 25)
anim.addAnimationFrame(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . f f f f f f . . . . 
    . . . . f f 1 1 1 1 f 1 f . . . 
    . . . f 1 1 5 5 5 f 1 1 1 f . . 
    . f f f f 5 5 5 f 1 1 f 1 1 f . 
    f 1 1 1 1 f 5 5 f 1 1 f 1 1 f . 
    f 1 1 1 1 1 f 5 f 1 1 1 1 1 f . 
    f 5 1 1 1 5 f 5 5 f f f f f f f 
    . f 5 5 5 f 5 5 f 2 2 2 2 2 2 f 
    . . f f f 4 4 f 2 f f f f f f f 
    . . . f 4 4 4 4 f 2 2 2 2 2 2 f 
    . . . . f f 4 4 4 f f f f f f . 
    . . . . . . f f f . . . . . . . 
    . . . . . . . . . . . . . . . . 
    `)
anim.addAnimationFrame(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . f f f f f f . . . . 
    . . . . f f 1 1 1 1 f 1 f . . . 
    . . . f 1 1 5 5 5 f 1 1 1 f . . 
    . f f f f 5 5 5 f 1 1 f 1 1 f . 
    f 1 1 1 1 f 5 5 f 1 1 f 1 1 f . 
    f 1 1 1 1 1 f 5 f 1 1 1 1 1 f . 
    f 5 1 1 1 5 f 5 5 f f f f f f f 
    . f 5 5 5 f 5 5 f 2 2 2 2 2 2 f 
    . . f f f 4 4 f 2 f f f f f f f 
    . . . f 4 4 4 4 f 2 2 2 2 2 2 f 
    . . . . f f 4 4 4 f f f f f f . 
    . . . . . . f f f . . . . . . . 
    . . . . . . . . . . . . . . . . 
    `)
anim.addAnimationFrame(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . f f f f f f . . . . 
    . . . . f f 1 1 1 1 f 1 f . . . 
    . . . f 1 1 5 5 5 f 1 1 1 f . . 
    . f f f f 5 5 5 f 1 1 f 1 1 f . 
    f 1 1 1 1 f 5 5 f 1 1 f 1 1 f . 
    f 1 1 1 1 1 f 5 f 1 1 1 1 1 f . 
    f 5 1 1 1 5 f 5 5 f f f f f f f 
    . f 5 5 5 f 5 5 f 2 2 2 2 2 2 f 
    . . f f f 4 4 f 2 f f f f f f f 
    . . . f 4 4 4 4 f 2 2 2 2 2 2 f 
    . . . . f f 4 4 4 f f f f f f . 
    . . . . . . f f f . . . . . . . 
    . . . . . . . . . . . . . . . . 
    `)
anim.addAnimationFrame(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . f f f f f f . . . . 
    . . . . f f 1 1 1 1 f 1 f . . . 
    . . . f 1 1 5 5 5 f 1 1 1 f . . 
    . f f f f 5 5 5 f 1 1 f 1 1 f . 
    f 1 1 1 1 f 5 5 f 1 1 f 1 1 f . 
    f 1 1 1 1 1 f 5 f 1 1 1 1 1 f . 
    f 5 1 1 1 5 f 5 5 f f f f f f f 
    . f 5 5 5 f 5 5 f 2 2 2 2 2 2 f 
    . . f f f 4 4 f 2 f f f f f f f 
    . . . f 4 4 4 4 f 2 2 2 2 2 2 f 
    . . . . f f 4 4 4 f f f f f f . 
    . . . . . . f f f . . . . . . . 
    . . . . . . . . . . . . . . . . 
    `)
anim.addAnimationFrame(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . f f f f f f . . . . 
    . . . . f f 1 1 1 1 f 1 f . . . 
    . . . f 1 1 5 5 5 f 1 1 1 f . . 
    . f f f f 5 5 5 f 1 1 f 1 1 f . 
    f 1 1 1 1 f 5 5 f 1 1 f 1 1 f . 
    f 1 1 1 1 1 f 5 f 1 1 1 1 1 f . 
    f 5 1 1 1 5 f 5 5 f f f f f f f 
    . f 5 5 5 f 5 5 f 2 2 2 2 2 2 f 
    . . f f f 4 4 f 2 f f f f f f f 
    . . . f 4 4 4 4 f 2 2 2 2 2 2 f 
    . . . . f f 4 4 4 f f f f f f . 
    . . . . . . f f f . . . . . . . 
    . . . . . . . . . . . . . . . . 
    `)
anim.addAnimationFrame(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . f f f f f f . . . . 
    . . . . f f 1 1 1 1 f 1 f . . . 
    . . . f 1 1 5 5 5 f 1 1 1 f . . 
    . f f f f 5 5 5 f 1 1 f 1 1 f . 
    f 1 1 1 1 f 5 5 f 1 1 f 1 1 f . 
    f 1 1 1 1 1 f 5 f 1 1 1 1 1 f . 
    f 5 1 1 1 5 f 5 5 f f f f f f f 
    . f 5 5 5 f 5 5 f 2 2 2 2 2 2 f 
    . . f f f 4 4 f 2 f f f f f f f 
    . . . f 4 4 4 4 f 2 2 2 2 2 2 f 
    . . . . f f 4 4 4 f f f f f f . 
    . . . . . . f f f . . . . . . . 
    . . . . . . . . . . . . . . . . 
    `)
anim.addAnimationFrame(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . f f f f f f . . . . 
    . . . . f f 1 1 1 1 f 1 f . . . 
    . . . f 1 1 5 5 5 f 1 1 1 f . . 
    . f f f f 5 5 5 f 1 1 f 1 1 f . 
    f 1 1 1 1 f 5 5 f 1 1 f 1 1 f . 
    f 1 1 1 1 1 f 5 f 1 1 1 1 1 f . 
    f 5 1 1 1 5 f 5 5 f f f f f f f 
    . f 5 5 5 f 5 5 f 2 2 2 2 2 2 f 
    . . f f f 4 4 f 2 f f f f f f f 
    . . . f 4 4 4 4 f 2 2 2 2 2 2 f 
    . . . . f f 4 4 4 f f f f f f . 
    . . . . . . f f f . . . . . . . 
    . . . . . . . . . . . . . . . . 
    `)
animation.attachAnimation(Mysprite, anim)
game.onUpdate(function () {
    if (Mysprite.vy < 0) {
        animation.setAction(Mysprite, ActionKind.Walking)
    }
    if (Mysprite.bottom > 120 || Mysprite.top < 0) {
        game.gameOver(false)
    }
})
game.onUpdateInterval(1500, function () {
    gap = randint(0, 3)
    if (gap == 0) {
        Tops = img`
            .....6eeeeeeeeeece6.....
            ....6776eeeeeeeee676....
            ...6776666eeee6766776...
            ..6776ee77777777667776..
            ...668ce7768867788666...
            ......ce77eeee67ee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......beeeeeeeeeeb......
            .......beeeeeeeeb.......
            ........beeeeeeb........
            `
        Bottom = img`
            ........................
            ........................
            ..........bbbb..........
            ........bbddddbb........
            .......bddbbbbddb.......
            ......bdbbddddbbdb......
            .....bdbbdbbbbdbbdb.....
            .....bdbdbddddbdbdb.....
            .....cdbbdbbbbdbbdc.....
            .....cbdbbddddbbdbc.....
            .....efbddbbbbddbce.....
            .....eeffbddddbccee.....
            .....eeeeffcccceee......
            .....ceeeeeeeeeeee......
            .....ceeeeeeeeeeee......
            .....feeeeeeeeeeee......
            .....cceeeeeeeeeee......
            ......feeeeeeeeeee......
            .....6fceeeeeeeeee6.....
            ....6776eeeeeeeee676....
            ...6777666eeee6666776...
            ..67768e67766777667776..
            ...668ee7768867788666...
            ......ee77eeee77ecee....
            ......ee6eeeeee6eef.....
            ......eeeeeeeeeeeef.....
            ......eeeeeeeeeeeef.....
            ......eeeeeeeeeeecf.....
            ......ceeeeeeeeeecf.....
            ......ceeeeeeeeeeff.....
            ......feeeeeeeeeefe.....
            .....6feeeeeeeeeef6.....
            ....6776eeeeeeeee676....
            ...6777666eeee6667776...
            ..6776ee67777777667776..
            ...668ee7768867788666...
            ......ee77eeee67ee......
            ......ee6eeeeee6ce......
            ......eefeeeeeeece......
            ......eeceeeeeeece......
            ......eeceeeeeeefe......
            ......eeceeeeeeefe......
            ......eeeeeeeeeefe......
            ......eeeeeeeeeece......
            .....6eeeeeeeeeece6.....
            ....6776eeeeeeeee676....
            ...6776666eeee6766776...
            ..6776ee77777777667776..
            ...668ce7768867788666...
            ......ce77eeee67ee......
            ......ce6eeeeee6ee......
            ......ceeeeeeeeeee......
            ......fcceeeeeecee......
            ......fccceeececce......
            ......fcceeecceccc......
            ......fccceecceccc......
            ......fccccceceecc......
            .....6fccccccccccf6.....
            ....6776ccccccccc676....
            ...6776676cccc6766776...
            ..6776cc77777777667776..
            ...668cc7768867788666...
            ......cc77cccc67cf......
            ......cc6cccccc6cf......
            `
    } else if (gap == 1) {
        Tops = img`
            .....6feeeeeeeeeef6.....
            ....6776eeeeeeeee676....
            ...6777666eeee6667776...
            ..6776ee67777777667776..
            ...668ee7768867788666...
            ......ee77eeee67ee......
            ......ee6eeeeee6ce......
            ......eefeeeeeeece......
            ......eeceeeeeeece......
            ......eeceeeeeeefe......
            ......eeceeeeeeefe......
            ......eeeeeeeeeefe......
            ......eeeeeeeeeece......
            .....6eeeeeeeeeece6.....
            ....6776eeeeeeeee676....
            ...6776666eeee6766776...
            ..6776ee77777777667776..
            ...668ce7768867788666...
            ......ce77eeee67ee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......beeeeeeeeeeb......
            .......beeeeeeeeb.......
            ........beeeeeeb........
            ........................
            ........................
            ........................
            `
        Bottom = img`
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ..........bbbb..........
            ........bbddddbb........
            .......bddbbbbddb.......
            ......bdbbddddbbdb......
            .....bdbbdbbbbdbbdb.....
            .....bdbdbddddbdbdb.....
            .....cdbbdbbbbdbbdc.....
            .....cbdbbddddbbdbc.....
            .....efbddbbbbddbce.....
            .....eeffbddddbccee.....
            .....eeeeffcccceee......
            .....ceeeeeeeeeeee......
            .....ceeeeeeeeeeee......
            .....feeeeeeeeeeee......
            .....cceeeeeeeeeee......
            ......feeeeeeeeeee......
            .....6fceeeeeeeeee6.....
            ....6776eeeeeeeee676....
            ...6777666eeee6666776...
            ..67768e67766777667776..
            ...668ee7768867788666...
            ......ee77eeee77ecee....
            ......ee6eeeeee6eef.....
            ......eeeeeeeeeeeef.....
            ......eeeeeeeeeeeef.....
            ......eeeeeeeeeeecf.....
            ......ceeeeeeeeeecf.....
            ......ceeeeeeeeeeff.....
            ......feeeeeeeeeefe.....
            .....6feeeeeeeeeef6.....
            ....6776eeeeeeeee676....
            ...6777666eeee6667776...
            ..6776ee67777777667776..
            ...668ee7768867788666...
            ......ee77eeee67ee......
            ......ee6eeeeee6ce......
            ......eefeeeeeeece......
            ......eeceeeeeeece......
            ......eeceeeeeeefe......
            ......eeceeeeeeefe......
            ......eeeeeeeeeefe......
            ......eeeeeeeeeece......
            .....6eeeeeeeeeece6.....
            ....6776eeeeeeeee676....
            ...6776666eeee6766776...
            ..6776ee77777777667776..
            ...668ce7768867788666...
            ......ce77eeee67ee......
            ......ce6eeeeee6ee......
            `
    } else if (gap == 2) {
        Tops = img`
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ..........bbbb..........
            ........bbddddbb........
            .......bddbbbbddb.......
            ......bdbbddddbbdb......
            .....bdbbdbbbbdbbdb.....
            .....bdbdbddddbdbdb.....
            .....cdbbdbbbbdbbdc.....
            .....cbdbbddddbbdbc.....
            .....efbddbbbbddbce.....
            .....eeffbddddbccee.....
            .....eeeeffcccceee......
            .....ceeeeeeeeeeee......
            .....ceeeeeeeeeeee......
            .....feeeeeeeeeeee......
            .....cceeeeeeeeeee......
            ......feeeeeeeeeee......
            .....6fceeeeeeeeee6.....
            ....6776eeeeeeeee676....
            ...6777666eeee6666776...
            ..67768e67766777667776..
            ...668ee7768867788666...
            ......ee77eeee77ecee....
            ......ee6eeeeee6eef.....
            ......eeeeeeeeeeeef.....
            ......eeeeeeeeeeeef.....
            ......eeeeeeeeeeecf.....
            ......ceeeeeeeeeecf.....
            ......ceeeeeeeeeeff.....
            ......feeeeeeeeeefe.....
            .....6feeeeeeeeeef6.....
            ....6776eeeeeeeee676....
            ...6777666eeee6667776...
            ..6776ee67777777667776..
            ...668ee7768867788666...
            ......ee77eeee67ee......
            ......ee6eeeeee6ce......
            ......eefeeeeeeece......
            ......eeceeeeeeece......
            ......eeceeeeeeefe......
            ......eeceeeeeeefe......
            ......eeeeeeeeeefe......
            ......eeeeeeeeeece......
            .....6eeeeeeeeeece6.....
            ....6776eeeeeeeee676....
            ...6776666eeee6766776...
            ..6776ee77777777667776..
            ...668ce7768867788666...
            ......ce77eeee67ee......
            ......ce6eeeeee6ee......
            `
        Bottom = img`
            ........................
            ........................
            ........................
            ........................
            ..........bbbb..........
            ........bbddddbb........
            .......bddbbbbddb.......
            ......bdbbddddbbdb......
            .....bdbbdbbbbdbbdb.....
            .....bdbdbddddbdbdb.....
            .....cdbbdbbbbdbbdc.....
            .....cbdbbddddbbdbc.....
            .....efbddbbbbddbce.....
            .....eeffbddddbccee.....
            .....eeeeffcccceee......
            .....ceeeeeeeeeeee......
            .....ceeeeeeeeeeee......
            .....feeeeeeeeeeee......
            .....cceeeeeeeeeee......
            ......feeeeeeeeeee......
            .....6fceeeeeeeeee6.....
            ....6776eeeeeeeee676....
            ...6777666eeee6666776...
            ..67768e67766777667776..
            ...668ee7768867788666...
            ......ee77eeee77ecee....
            ......ee6eeeeee6eef.....
            ......eeeeeeeeeeeef.....
            ......eeeeeeeeeeeef.....
            ......eeeeeeeeeeecf.....
            ......ceeeeeeeeeecf.....
            ......ceeeeeeeeeeff.....
            ......feeeeeeeeeefe.....
            .....6feeeeeeeeeef6.....
            ....6776eeeeeeeee676....
            ...6777666eeee6667776...
            ..6776ee67777777667776..
            ...668ee7768867788666...
            ......ee77eeee67ee......
            ......ee6eeeeee6ce......
            `
    } else {
        Tops = img`
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ..........bbbb..........
            ........bbddddbb........
            .......bddbbbbddb.......
            ......bdbbddddbbdb......
            .....bdbbdbbbbdbbdb.....
            .....bdbdbddddbdbdb.....
            .....cdbbdbbbbdbbdc.....
            .....cbdbbddddbbdbc.....
            .....efbddbbbbddbce.....
            .....eeffbddddbccee.....
            .....eeeeffcccceee......
            .....ceeeeeeeeeeee......
            .....ceeeeeeeeeeee......
            .....feeeeeeeeeeee......
            .....cceeeeeeeeeee......
            ......feeeeeeeeeee......
            .....6fceeeeeeeeee6.....
            ....6776eeeeeeeee676....
            ...6777666eeee6666776...
            ..67768e67766777667776..
            ...668ee7768867788666...
            ......ee77eeee77ecee....
            ......ee6eeeeee6eef.....
            ......eeeeeeeeeeeef.....
            ......eeeeeeeeeeeef.....
            ......eeeeeeeeeeecf.....
            ......ceeeeeeeeeecf.....
            ......ceeeeeeeeeeff.....
            ......feeeeeeeeeefe.....
            .....6feeeeeeeeeef6.....
            ....6776eeeeeeeee676....
            ...6777666eeee6667776...
            ..6776ee67777777667776..
            ...668ee7768867788666...
            ......ee77eeee67ee......
            ......ee6eeeeee6ce......
            ......eefeeeeeeece......
            ......eeceeeeeeece......
            ......eeceeeeeeefe......
            ......eeceeeeeeefe......
            ......eeeeeeeeeefe......
            ......eeeeeeeeeece......
            .....6eeeeeeeeeece6.....
            ....6776eeeeeeeee676....
            ...6776666eeee6766776...
            ..6776ee77777777667776..
            ...668ce7768867788666...
            ......ce77eeee67ee......
            ......ce6eeeeee6ee......
            `
        Bottom = img`
            ........................
            ........................
            ........................
            ........................
            ..........bbbb..........
            ........bbddddbb........
            .......bddbbbbddb.......
            ......bdbbddddbbdb......
            .....bdbbdbbbbdbbdb.....
            .....bdbdbddddbdbdb.....
            .....cdbbdbbbbdbbdc.....
            .....cbdbbddddbbdbc.....
            .....efbddbbbbddbce.....
            .....eeffbddddbccee.....
            .....eeeeffcccceee......
            .....ceeeeeeeeeeee......
            .....ceeeeeeeeeeee......
            .....feeeeeeeeeeee......
            .....cceeeeeeeeeee......
            ......feeeeeeeeeee......
            .....6fceeeeeeeeee6.....
            ....6776eeeeeeeee676....
            ...6777666eeee6666776...
            ..67768e67766777667776..
            ...668ee7768867788666...
            ......ee77eeee77ecee....
            ......ee6eeeeee6eef.....
            ......eeeeeeeeeeeef.....
            ......eeeeeeeeeeeef.....
            ......eeeeeeeeeeecf.....
            ......ceeeeeeeeeecf.....
            ......ceeeeeeeeeeff.....
            ......feeeeeeeeeefe.....
            .....6feeeeeeeeeef6.....
            ....6776eeeeeeeee676....
            ...6777666eeee6667776...
            ..6776ee67777777667776..
            ...668ee7768867788666...
            ......ee77eeee67ee......
            ......ee6eeeeee6ce......
            `
    }
    gapimage = image.create(2, scene.screenHeight())
    gapimage.fill(1)
    gapSprite = sprites.create(gapimage, SpriteKind.Gapkind)
    gapSprite.setFlag(SpriteFlag.AutoDestroy, true)
    gapSprite.setFlag(SpriteFlag.Invisible, true)
    gapSprite.left = scene.screenWidth()
    gapSprite.vx = -45
    projectile = sprites.createProjectileFromSide(Tops, -45, 0)
    projectile.top = 0
    projectile = sprites.createProjectileFromSide(Bottom, -45, 0)
    projectile.bottom = scene.screenHeight()
})
